title: "Tessa Cicak"
author: "Tessa Cicak"
description: "University of Minnesota, Twin Cities"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV"}
  - {title: "About"}
  - {title: "Workshops"}
  - {title: "Ongoing Projects"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Contact, icon: envelope, url: "mailto:cicak001@umn.edu"}
  #- {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
